version: '3.3'

networks:
  frontend:
    ipam:
      config:
      - subnet: 172.19.0.0/16

services:
  coursehunters:
    container_name: "coursehunters"
    build: "./docker/coursehunters"
    volumes:
    - ".:${GO_PROJECT_DIR}"
    networks:
      frontend:
        ipv4_address: $WEB_SERVICE_HOST
    ports:
    - "80:8080"
    env_file:
    - .env
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/app"
  db:
    image: mongo:4.1.5
    env_file:
      - .env
    networks:
      frontend:
        ipv4_address: $MONGO_HOST
    ports:
    - "5432:5432"